export const products = [
  {
    id: "1",
    slug: "glass-fermentation-jar",
    name: "Glass Fermentation Jar",
    category: "kombucha",
    price: 34.99,
    image: "/glass-fermentation-jar-with-kombucha.jpg",
    images: ["/glass-fermentation-jar-with-kombucha.jpg"],
    description:
      "Premium 1-gallon glass fermentation jar perfect for kombucha, water kefir, and other fermented beverages.",
    features: [
      "Lead-free borosilicate glass",
      "Wide mouth for easy access",
      "Includes cotton cover and rubber band",
      "Dishwasher safe",
    ],
    materials: "100% recycled borosilicate glass",
    sustainability: "Made from post-consumer recycled glass, reducing landfill waste by 95%",
    idealFor: ["Kombucha", "Water Kefir", "Jun Tea", "Vinegar"],
    amazonLink: "#",
    rating: 4.8,
    reviews: 234,
  },
  {
    id: "2",
    slug: "brewing-thermometer-pro",
    name: "Brewing Thermometer Pro",
    category: "all",
    price: 24.99,
    image: "/digital-brewing-thermometer.jpg",
    images: ["/digital-brewing-thermometer.jpg"],
    description: "Digital precision thermometer designed for fermentation monitoring with 0.1°F accuracy.",
    features: ["0.1°F precision", "Waterproof probe", "Memory function", "Auto-off feature"],
    materials: "Stainless steel probe, ABS plastic housing",
    sustainability: "Low-power consumption, replaceable battery design",
    idealFor: ["All ferments", "Temperature monitoring", "Brewing precision"],
    amazonLink: "#",
    rating: 4.9,
    reviews: 189,
  },
  {
    id: "3",
    slug: "bamboo-lid-set",
    name: "Bamboo Lid Set",
    category: "kombucha",
    price: 19.99,
    image: "/bamboo-brewing-lid-set.jpg",
    images: ["/bamboo-brewing-lid-set.jpg"],
    description: "Set of 3 bamboo fermentation lids with built-in ventilation for healthy cultures.",
    features: [
      "Natural antibacterial properties",
      "Built-in airlock system",
      "Fits standard mason jars",
      "Set of 3 sizes",
    ],
    materials: "100% sustainably sourced bamboo",
    sustainability: "Bamboo regenerates 30x faster than trees, zero plastic packaging",
    idealFor: ["Kombucha", "Fermenting vegetables", "Sourdough starter"],
    amazonLink: "#",
    rating: 4.7,
    reviews: 156,
  },
  {
    id: "4",
    slug: "ceramic-kvass-crock",
    name: "Ceramic Kvass Crock",
    category: "kvass",
    price: 59.99,
    image: "/ceramic-fermentation-crock.jpg",
    images: ["/ceramic-fermentation-crock.jpg"],
    description: "Traditional 2-gallon ceramic crock with water seal for authentic kvass brewing.",
    features: ["Water-sealed lid", "Lead-free glaze", "Thick walls for temperature stability", "Includes weights"],
    materials: "Food-safe stoneware ceramic",
    sustainability: "Handcrafted by local artisans, built to last generations",
    idealFor: ["Kvass", "Sauerkraut", "Kimchi", "Large batch ferments"],
    amazonLink: "#",
    rating: 4.9,
    reviews: 98,
  },
  {
    id: "5",
    slug: "honey-mead-starter-kit",
    name: "Honey Mead Starter Kit",
    category: "mead",
    price: 89.99,
    image: "/mead-brewing-starter-kit.jpg",
    images: ["/mead-brewing-starter-kit.jpg"],
    description: "Complete mead brewing kit with everything needed to craft your first batch of honey wine.",
    features: ["1-gallon carboy", "Airlock and stopper", "Yeast and nutrients included", "Step-by-step guide"],
    materials: "Glass carboy, food-grade silicone, organic honey",
    sustainability: "Partnered with sustainable apiaries for raw honey sourcing",
    idealFor: ["Mead", "Metheglin", "Cyser", "Beginners"],
    amazonLink: "#",
    rating: 4.8,
    reviews: 312,
  },
  {
    id: "6",
    slug: "botanical-infuser-set",
    name: "Botanical Infuser Set",
    category: "botanical",
    price: 44.99,
    image: "/botanical-infusion-brewing-set.jpg",
    images: ["/botanical-infusion-brewing-set.jpg"],
    description: "Premium stainless steel infuser set for adding herbs, fruits, and botanicals to your brews.",
    features: [
      "Fine mesh for no sediment",
      "Multiple sizes included",
      "Long handles for deep vessels",
      "Easy to clean",
    ],
    materials: "304 stainless steel",
    sustainability: "Lifetime warranty, eliminates single-use tea bags",
    idealFor: ["Botanical ferments", "Herbal infusions", "Fruit additions", "Tea blends"],
    amazonLink: "#",
    rating: 4.6,
    reviews: 145,
  },
  {
    id: "7",
    slug: "temperature-controller",
    name: "Temperature Controller",
    category: "all",
    price: 79.99,
    image: "/fermentation-temperature-controller.jpg",
    images: ["/fermentation-temperature-controller.jpg"],
    description: "Digital temperature controller with heating and cooling outputs for precise fermentation control.",
    features: ["Dual heating/cooling", "1°F accuracy", "Programmable cycles", "Energy efficient"],
    materials: "ABS housing, stainless steel probe",
    sustainability: "Energy Star rated, reduces power consumption by 40%",
    idealFor: ["Year-round brewing", "Temperature-sensitive cultures", "Professional results"],
    amazonLink: "#",
    rating: 4.9,
    reviews: 267,
  },
  {
    id: "8",
    slug: "glass-bottles-6-pack",
    name: "Glass Bottles 6-Pack",
    category: "all",
    price: 29.99,
    image: "/swing-top-glass-bottles-for-brewing.jpg",
    images: ["/swing-top-glass-bottles-for-brewing.jpg"],
    description: "Set of 6 swing-top glass bottles perfect for secondary fermentation and carbonation.",
    features: ["Pressure-rated glass", "Airtight swing-top seal", "16oz capacity each", "Amber glass option"],
    materials: "Thick-walled recycled glass, stainless steel tops",
    sustainability: "Made from 100% recycled glass, infinitely reusable",
    idealFor: ["Carbonation", "Storage", "Gifting", "All bottled ferments"],
    amazonLink: "#",
    rating: 4.7,
    reviews: 423,
  },
  {
    id: "9",
    slug: "ph-testing-kit",
    name: "pH Testing Kit",
    category: "all",
    price: 15.99,
    image: "/ph-testing-kit-for-brewing.jpg",
    images: ["/ph-testing-kit-for-brewing.jpg"],
    description: "Complete pH testing kit with strips and calibration solutions for monitoring fermentation acidity.",
    features: ["100 test strips", "Wide pH range (1-14)", "Color comparison chart", "Calibration solutions included"],
    materials: "Non-toxic testing strips, recyclable packaging",
    sustainability: "Plastic-free packaging, biodegradable strips",
    idealFor: ["All ferments", "Safety monitoring", "Quality control"],
    amazonLink: "#",
    rating: 4.5,
    reviews: 189,
  },
]

export const categories = [
  { id: "all", label: "All Equipment" },
  { id: "kombucha", label: "Kombucha" },
  { id: "kvass", label: "Kvass" },
  { id: "mead", label: "Mead" },
  { id: "botanical", label: "Botanical" },
]

export const drinks = [
  {
    id: "kombucha",
    name: "Kombucha",
    description:
      "A fermented tea beverage made with a symbiotic culture of bacteria and yeast (SCOBY). Known for its probiotic benefits and tangy, slightly sweet taste.",
    image: "/kombucha-drink-glass.jpg",
    origin: "China, ~220 BCE",
    fermentTime: "7-14 days",
    difficulty: "Beginner",
    ingredients: ["Tea", "Sugar", "SCOBY", "Starter liquid"],
  },
  {
    id: "chicha-morada",
    name: "Chicha Morada",
    description:
      "A traditional Peruvian beverage made from purple corn, spiced with cinnamon and cloves. Sweet, fruity, and deeply refreshing.",
    image: "/chicha-morada-purple-corn-drink.jpg",
    origin: "Peru, Pre-Columbian era",
    fermentTime: "2-3 days (for fermented version)",
    difficulty: "Beginner",
    ingredients: ["Purple corn", "Pineapple", "Cinnamon", "Cloves", "Lime"],
  },
  {
    id: "ginger-beer",
    name: "Ginger Beer",
    description:
      "A spicy, effervescent fermented beverage made with fresh ginger. Perfect for cocktails or enjoyed on its own.",
    image: "/ginger-beer-brewing.jpg",
    origin: "England, 18th century",
    fermentTime: "3-5 days",
    difficulty: "Beginner",
    ingredients: ["Fresh ginger", "Sugar", "Lemon", "Ginger bug starter"],
  },
  {
    id: "jun-tea",
    name: "Jun Tea",
    description:
      "Often called the 'champagne of kombucha,' Jun is fermented with green tea and raw honey for a lighter, more delicate flavor.",
    image: "/jun-tea-green-honey.jpg",
    origin: "Tibet (disputed)",
    fermentTime: "5-7 days",
    difficulty: "Intermediate",
    ingredients: ["Green tea", "Raw honey", "Jun SCOBY", "Starter"],
  },
  {
    id: "kvass",
    name: "Kvass",
    description:
      "A traditional Slavic beverage made from fermented rye bread. Mildly alcoholic with an earthy, slightly sour flavor.",
    image: "/kvass-rye-bread-drink.jpg",
    origin: "Russia/Ukraine, 10th century",
    fermentTime: "2-4 days",
    difficulty: "Beginner",
    ingredients: ["Rye bread", "Sugar", "Raisins", "Yeast"],
  },
  {
    id: "mead",
    name: "Mead",
    description:
      "The ancient honey wine, one of humanity's oldest alcoholic beverages. Ranges from sweet to dry with infinite flavor variations.",
    image: "/mead-honey-wine-glass.jpg",
    origin: "Africa/Europe, 7000 BCE",
    fermentTime: "4-6 weeks (primary)",
    difficulty: "Intermediate",
    ingredients: ["Honey", "Water", "Yeast", "Nutrients"],
  },
]

export const guides = [
  {
    slug: "fermentation-science",
    title: "The Science of Fermentation",
    description:
      "Understanding the biology behind the bubbles — how microorganisms transform simple sugars into complex flavors.",
    readTime: "8 min read",
    category: "Science",
    content: `Fermentation is one of nature's oldest biotechnological processes...`,
  },
  {
    slug: "mead-modern-tools",
    title: "How to Brew Mead with Modern Tools",
    description: "Ancient honey wine meets contemporary technique for consistent, delicious results.",
    readTime: "12 min read",
    category: "Tutorial",
    content: `Mead, the ancient drink of Vikings and Greek gods...`,
  },
  {
    slug: "keeping-kombucha-alive",
    title: "Keeping Your Kombucha Alive",
    description: "SCOBY care and maintenance guide for healthy, thriving cultures.",
    readTime: "6 min read",
    category: "Care",
    content: `Your SCOBY is a living organism that requires attention...`,
  },
  {
    slug: "temperature-control",
    title: "Best Temperature Control for Ferments",
    description: "Precision brewing for consistent results year-round.",
    readTime: "10 min read",
    category: "Equipment",
    content: `Temperature is perhaps the most critical variable in fermentation...`,
  },
]
